export const FFMPEG_CHANNELS = {
  START_PROCESS: "ffmpeg:start",
  CANCEL_PROCESS: "ffmpeg:cancel",
  PROGRESS_UPDATE: "ffmpeg:progress",
  LOG_OUTPUT: "ffmpeg:log",
  PROCESS_COMPLETE: "ffmpeg:complete",
  PROCESS_ERROR: "ffmpeg:error",
  SELECT_VIDEO_FILE: "ffmpeg:selectVideo",
  SELECT_SUBTITLE_FILE: "ffmpeg:selectSubtitle",
  SELECT_OUTPUT_PATH: "ffmpeg:selectOutput",
  GET_DEFAULT_OUTPUT_PATH: "ffmpeg:getDefaultOutputPath",
  CHECK_GPU: "ffmpeg:checkGpu",
  OPEN_OUTPUT_FOLDER: "ffmpeg:openOutputFolder",
  // Output conflict detection
  CHECK_OUTPUT_EXISTS: "ffmpeg:checkOutputExists",
  RESOLVE_OUTPUT_CONFLICT: "ffmpeg:resolveOutputConflict",
  // FFmpeg Download
  CHECK_INSTALLED: "ffmpeg:checkInstalled",
  START_DOWNLOAD: "ffmpeg:startDownload",
  DOWNLOAD_PROGRESS: "ffmpeg:downloadProgress",
  DOWNLOAD_COMPLETE: "ffmpeg:downloadComplete",
  DOWNLOAD_ERROR: "ffmpeg:downloadError",
  // Queue Management
  QUEUE_ADD_ITEM: "ffmpeg:queue:addItem",
  QUEUE_ADD_ITEMS: "ffmpeg:queue:addItems",
  QUEUE_REMOVE_ITEM: "ffmpeg:queue:removeItem",
  QUEUE_CLEAR: "ffmpeg:queue:clear",
  QUEUE_REORDER: "ffmpeg:queue:reorder",
  QUEUE_START: "ffmpeg:queue:start",
  QUEUE_PAUSE: "ffmpeg:queue:pause",
  QUEUE_RESUME: "ffmpeg:queue:resume",
  QUEUE_GET_ALL: "ffmpeg:queue:getAll",
  QUEUE_GET_STATS: "ffmpeg:queue:getStats",
  QUEUE_UPDATE_SETTINGS: "ffmpeg:queue:updateSettings",
  QUEUE_SELECT_FILES: "ffmpeg:queue:selectFiles",
  QUEUE_UPDATE_ITEM_OUTPUT: "ffmpeg:queue:updateItemOutput",
  // Queue Events
  QUEUE_UPDATE: "ffmpeg:queue:update",
  QUEUE_ITEM_UPDATE: "ffmpeg:queue:itemUpdate",
  QUEUE_ITEM_PROGRESS: "ffmpeg:queue:itemProgress",
  QUEUE_ITEM_LOG: "ffmpeg:queue:itemLog",
  QUEUE_ITEM_COMPLETE: "ffmpeg:queue:itemComplete",
  QUEUE_ITEM_ERROR: "ffmpeg:queue:itemError",
  QUEUE_COMPLETE: "ffmpeg:queue:complete",
  // Disk Space Check
  CHECK_DISK_SPACE: "ffmpeg:checkDiskSpace",
  GET_DISK_SPACE: "ffmpeg:getDiskSpace",
  GET_VIDEO_DURATION: "ffmpeg:getVideoDuration",
} as const;
